/*
 * This C++ source file was generated by the Gradle 'init' task.
 */

#include "cpp_rtmp.h"
#include <cassert>

int main() {
    cpp_rtmp::Greeter greeter;
    assert(greeter.greeting().compare("Hello, World!") == 0);
    return 0;
}
