/*
 * This C++ source file was generated by the Gradle 'init' task.
 */

#include <iostream>
#include <stdlib.h>
#include "cpp_rtmp.h"

std::string cpp_rtmp::Greeter::greeting() {
    return std::string("Hello, World!");
}
