/*
 * This C++ source file was generated by the Gradle 'init' task.
 */
#ifndef CPP_RTMP_H
#define CPP_RTMP_H

#ifdef _WIN32
#define CPP_RTMP_EXPORT_FUNC __declspec(dllexport)
#else
#define CPP_RTMP_EXPORT_FUNC
#endif

#include <string>

namespace cpp_rtmp {
    class Greeter {
        public:
        std::string CPP_RTMP_EXPORT_FUNC greeting();
    };
}

#endif
